version: '3.8'

services:
  media:
    image: lscr.io/linuxserver/plex:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
    volumes:
      - /home/dima/media-go/workdir/config/plex/config:/config
      - /home/dima/media-go/workdir/mediadata_main:/movies/1
      - /home/dima/media/workdir/mediadata_hdd/low_quality:/movies/2
    networks:
      - host
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
      placement:
        constraints:
          - "node.role == manager"


networks:
  host:
    external: true
