version: '3.8'

services:
  text:
    image: halushko/kino-cat-text-go:beta-latest
    environment:
      - BROKER_IP=nats
      - BROKER_PORT=4222
    volumes:
      - /home/dima/media-go/workdir/logs/text:/root/logs
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 5
      placement:
        constraints:
          - "node.role == manager"
    networks:
      - go_cat_network

networks:
  go_cat_network:
    external: true