services:
  bot:
    image: halushko/kino-cat-bot-go:beta-latest
    container_name: kino-cat-bot-go
    environment:
      - BOT_TOKEN=6953522453:AAHF5bZd6BEwTPKoFohdjA7bRKkQQajcUog
      - BROKER_IP=10.10.127.55
      - BROKER_PORT=4222
    volumes:
      - ./logs/bot:/root/logs
    depends_on:
      - nats
    networks:
      go-cat_private_network:
        ipv4_address: 10.10.127.11
  text:
    image: halushko/kino-cat-text-go:beta-latest
    container_name: kino-cat-text-go
    environment:
      - BROKER_IP=10.10.127.55
      - BROKER_PORT=4222
    volumes:
      - ./logs/text:/root/logs
    depends_on:
      - nats
    networks:
      go-cat_private_network:
        ipv4_address: 10.10.127.12
  file:
    image: halushko/kino-cat-file-go:beta-latest
    container_name: kino-cat-file-go
    environment:
      - BROKER_IP=10.10.127.55
      - BROKER_PORT=4222
      - BOT_TOKEN=6953522453:AAHF5bZd6BEwTPKoFohdjA7bRKkQQajcUog
    volumes:
      - ./logs/file:/root/logs
      - ./workdir/torrents_to_processed:/root/torrents_to_process
      - ./workdir/config/files_from_telegram_main:/root/torrents_to_download
      - ./workdir/config/files_db:/data
    depends_on:
      - nats
    networks:
      go-cat_private_network:
        ipv4_address: 10.10.127.13
  torrent:
    image: halushko/kino-cat-torrent-go:beta-latest
    container_name: kino-cat-torrent-go
    environment:
      - BROKER_IP=10.10.127.55
      - BROKER_PORT=4222
      - TORRENT_IP=10.10.127.77
      - TORRENT_PORT=9091
    volumes:
      - ./logs/torrent:/root/logs
      - ./config/servers/:/root/config
    depends_on:
      - nats
    networks:
      go-cat_private_network:
        ipv4_address: 10.10.127.14
  nats:
    image: nats:latest
    container_name: nats-server
    environment:
      - NATS_JS_STORE_DIR=/data/jetstream
    volumes:
      - ./nats_data:/data
    ports:
      - 4222:4222
    networks:
      go-cat_private_network:
        ipv4_address: 10.10.127.55
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: "transmission"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./workdir/config/transmission:/config
      - ./workdir/mediadata_main:/downloads/complete
      - ./workdir/mediadata_main:/downloads/incomplete
      - ./workdir/mediadata_backlog:/downloads/backlog
      - ./workdir/config/files_from_telegram_main:/watch
    ports:
      - 9091:9091
    networks:
      go-cat_private_network:
        ipv4_address: 10.10.127.77
  media:
    image: lscr.io/linuxserver/plex:latest
    container_name: "media"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
    volumes:
      - ./workdir/config/plex/config:/config
      - ./workdir/mediadata_main:/movies/1
      - ./workdir/mediadata_backlog:/movies/2
    restart: always
    networks:
      go-cat_private_network:
        ipv4_address: 10.10.127.88
networks:
  go-cat_private_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16